### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by LIUJUN-liujun** [martin-pr/possumwood#175]
Hello Professor:
During the installation of possumwood on Ubuntu 18.04 using PPA or Snap, we encountered the following problems. We don't know the reason, and we don't know how to solve these problems. Hope you can help us find a solution when you are free. Questions are as follows:
Warning: configuration file'possumwood.conf' not found!
terminate called after throwing an instance of'std::runtime_error'
   what(): Cannot expand path-variable PLUGINS not found
Aborted (core dumped)
Thanks a lot for your time.

**Comment by martin-pr** [comment]
Hey!

I am definitely not a professor :)

Yes, you're right, this seems to have broken during recent filesystem refactor. I believe I have a fix now - if it works, you should be able to pick up the changes tomorrow by updating.

Martin
